### ISSUE TITLE
IMessage doesn't send sms. No errors.

### ISSUE THREAD

**Issue by wisenlucky** [Rolstenhouse/py-iMessage#2]
Hi,
I am on MacOS Capatlina 10.15.3. I get no errors, I was able to execute csrutil disable. 

But For some reason, the script doesn't work. It opens Imessage sending menu ( screenshot: https://ibb.co/BB51qDW). Then script exits with code 0 and prints the read date of last message. 

Code I use - pretty straightforward one from the example ( see screenshot).

Any hint on how to fix it?

**Comment by chris-tracy** [comment]
I am having the same issue. Any resolution here?

**Comment by Rolstenhouse** [comment]
@wisenlucky @chris-tracy There seemed to be a bad merge that took place, I just updated the package so should be fixed!

Run the following to upgrade the package and let me know!
`pip install --upgrade --force-reinstall py-imessage`

**Comment by chris-tracy** [comment]
@Rolstenhouse It is working for me now. Thanks for the update!

**Comment by wisenlucky** [comment]
Yep works fine here! Thanks!
